### ISSUE TITLE
ImportError: No module named 'RuboCop'

### ISSUE THREAD

**Issue by davidalejandroaguilar** [pderichs/sublime_rubocop#60]
##### Please add some general information about your environment:

- Operating System: Ubuntu 16.04.5
- Sublime Text version: 3.1.1 Build 3176
- Details about your config e.g. do you use rbenv, rvm or your_own_command to run rubocop?: Using rbenv.

##### Steps to reproduce:

1. Added git repo using Package Control: Add Repository (because it is not listed otherwise)
2. Added sublime_rubocop using Package Control
3. Start Sublime

##### Error:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/david/.config/sublime-text-3/Installed Packages/sublime_rubocop.sublime-package/rubocop_command.py", line 7, in <module>
ImportError: No module named 'RuboCop'
reloading plugin sublime_rubocop.rubocop_listener
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/david/.config/sublime-text-3/Installed Packages/sublime_rubocop.sublime-package/rubocop_listener.py", line 8, in <module>
ImportError: No module named 'RuboCop'
```

**Comment by rnkyr** [comment]
faced the same issue. manual installation resolved it
